### ISSUE TITLE
Simulating axial asymmetric PSF

### ISSUE THREAD

**Issue by icbcbicc** [tlambert03/PSFmodels#32]
* psfmodels version: 0.3.3
* Python version: 3.11.5
* Operating System: Ubuntu 20.04

### Description

Hi, I was trying to simulate an axial asymmetric PSF. My goal is something like this <img width="866" alt="Screenshot 2024-02-14 at 17 58 49" src="https://github.com/tlambert03/PSFmodels/assets/12278291/1067d036-72a1-42ba-893b-ed62edf0f107"> where the PSF at $-20\mu m$ differs from the one at $20\mu m$ (image is taken from this [paper](https://doi.org/10.1364/BOE.446928)).

### What I Did

It is widely accepted that the asymmetry can be caused by the refractive index mismatch. So I've tried set $ni=1.0$ and $ns=1.33$. However, the result PSF is still symmetric w.r.t to z.

Code:
```   
psf = psfm.make_psf(z=np.linspace(-3, 3, 5),
                        NA=0.75,
                        dxy=0.25,
                        ni0=1.0,
                        ni=1.0,
                        ns=1.33,
                        nx=63,
                        model="vectorial")
```

In this case, psf[0] is the same as psf[-1].

Could you please point out what I am missing here? Thanks.

**Comment by tlambert03** [comment]
the theoretical impact of refractive index mismatch on spherical aberration depends on depth from the coverslip.  If the point emitter is *directly* on the coverslip (`pz=0`), then it really doesn't matter what the mismatch is, since effectively no marginal rays will experience the dramatic path-length difference.  So, you'll need to model a point source a bit deeper into the sample medium by using something like `z=np.linspace(5, 15, 15)` and `pz=10` (you can also use [`vectorial_psf_centered`](https://github.com/tlambert03/PSFmodels/blob/8d5737b7566ad6fd279ed7bbd080877b7c6828f5/src/psfmodels/_core.py#L368) as a convenience of you don't want to have to keep shifting your `linspace` params and `pz` together)

Also, the effect of RI mismatch and depth will be much more noticeable at higher NA.  So, by using NA 0.75 it's a bit harder to see it.

As an example, see the second figure in https://github.com/tlambert03/PSFmodels/blob/main/notebooks/examples.ipynb which models a point source 2 microns from the coverslip, at NA 1.42, with sample RI of 1.38 and immersion oil of 1.515

**Comment by tlambert03** [comment]
btw, if you want to play with an interactive example of spherical aberration at different depths, see this demo I made: https://cbmf.hms.harvard.edu/aberration/

the black rays are coming from the point source, and the dotted red rays are what would appear at the detector plane (superimposed over the sample rays for demonstration of aberration)

at depth of zero, everything is fine even though the sample RI (1.32) doesn't match the oil RI (1.515)

<img width="1310" alt="image" src="https://github.com/tlambert03/PSFmodels/assets/1609449/dffb04a8-f5f2-433b-a55f-26b9dec9703a">

only a the point source goes deeper, here to 2µm, do you see the impact on spherical aberration (note how the marginal red rays don't come to the same focal point as the paraxial rays)(

<img width="1310" alt="Screenshot 2024-02-14 at 8 34 20 PM" src="https://github.com/tlambert03/PSFmodels/assets/1609449/02c8342d-9f03-421f-b26f-baee1b110ae3">

**Comment by icbcbicc** [comment]
Thanks a lot. The notebook and the online demo are very helpful. I indeed notice the asymmetry in PSF once I increase pz.

The reason why I'm investigating this is that I want to figure out what is the major cause of asymmetry in the out-of-focus image at symmetrical z. For example, in the [figure](https://github.com/tlambert03/PSFmodels/assets/12278291/1067d036-72a1-42ba-893b-ed62edf0f107) I posted earlier, the image at -20µm and 20µm looks very different, not just in the level of blur, but also the blur pattern. I think this is due to two reasons:

- The first reason is the RI mismatch combined with a pz>0. 
- The second reason is that the sample is 3D instead of 2D. So by setting different z, we are focusing on different sections of the sample (this reason might be more important?).

I've tried convolving the generated asymmetrical PSFs (z=-20µm and z=20µm) with an in-focus image, while the blur level is different (due to pz>0), the blur pattern of the two generated images is very similar. However, the blur pattern of the generated images is very different from the actual image at -20µm and 20µm.

Thanks for your time!

**Comment by tlambert03** [comment]
I'm sorry, I'm not really following much of that

> I want to figure out what is the major cause of asymmetry in the out-of-focus image at symmetrical z

I'm not sure exactly what you mean here.  The major cause of axial asymmetry *is* spherical aberration... can you elaborate on what you mean by "figure out what is the major cause"?  Is this a theoretical/educational goal?  or a practical application goal?

> The second reason is that the sample is 3D instead of 2D. So by setting different z, we are focusing on different sections of the sample (this reason might be more important?).

not sure what you mean by "setting different z".  Do you mean changing the pz?

To accurately model image formation you would need to essentially convolve your 3D "ground truth" array (i.e. not just an "in focus image" but a map of fluorophore distrubution at extremely small sampling rate/pixel size) by a 3D PSF, but the PSF you convolve with would need to vary depending on the plane.
That's rather computationally complex, so most people just approximate it all by assuming shift invariance of the PSF (i.e. assuming that the PSF is the same for every point emitter in your sample)

> I've tried convolving the generated asymmetrical PSFs (z=-20µm and z=20µm) with an in-focus image, while the blur level is different (due to pz>0), the blur pattern of the two generated images is very similar. However, the blur pattern of the generated images is very different from the actual image at -20µm and 20µm.

also not quite following here.  Are you doing a 2D convolution with single out-of-focus planes plucked from a 3D PSF, with a single in-focus image?  see above for how you would generate/simulate image formation.   What exactly are you trying to achieve?

**Comment by tlambert03** [comment]
since there's nothing actionable for us to do here, I'm going to close this issue.  but you should feel free to keep asking questions as you have them!

**Comment by icbcbicc** [comment]
> if (and only if) you can model your tissue as an infinitely thin sample (or at least significantly thinner than the axial extent of the central maximum of the PSF), which is extremely co-planar with the focal plane (i.e. no coverslip tilt, etc...). then you can probably get close, but there's an additional point to remember: The out-of-focus planes can not be modeled as convolution of the in-focus plane with a specific out-of-focus slice from the PSF. The in-focus-plane itself is already the convolution of the sample distribution (i.e. the ground truth) with the in-focus PSF. So, if you convolve that image again by an out-of-focus PSF, then you're "double" convolving. You would technically need access to the ground truth (the "real" distribution of sample in your image) for this to work. Lacking that, there might be some clever tricks people have used, or perhaps ML ... but it's not as simple as a plain convolution

This makes a lot of sense. It seems like simulating this process is very difficult.

> is this your ultimate goal here? you want to know which direction is towards or away from the objective lens? What is your ultimate goal?

My ultimate goal is to develop a Focus Quality Assessment model using deep/machine learning.  The ground truth of most z-stack based datasets is the pz value (for example, [FocusPath](https://sites.google.com/view/focuspathuoft)). I'm wondering how should I justify the perceptual blurriness of images with pz that have opposite signs. Some works assume the images at pz=x and pz=-x have the same amount of blur. Since the blur pattern looks different to me, I'm wondering if this assumption is true or not, or is there any theory to improve it? BTW, I would also like to know which direction is towards or away from the objective lens.
